/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-05-17 05:30:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/view/user/userlist.jspf", Long.valueOf(1715657668320L));
    _jspx_dependants.put("/WEB-INF/view/user/userform.jspf", Long.valueOf(1715742299504L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.25.RELEASE.jar", Long.valueOf(1715309441093L));
    _jspx_dependants.put("jar:file:/C:/Users/NTPU/Documents/workspace-javaweb/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/SpringMVC/WEB-INF/lib/spring-webmvc-4.3.25.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1564703674000L));
    _jspx_dependants.put("/WEB-INF/view/user/userstatistics.jspf", Long.valueOf(1715589037347L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar", Long.valueOf(1715309440071L));
    _jspx_dependants.put("jar:file:/C:/Users/NTPU/Documents/workspace-javaweb/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/SpringMVC/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/c.tld", Long.valueOf(1420527028000L));
    _jspx_dependants.put("jar:file:/C:/Users/NTPU/Documents/workspace-javaweb/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/SpringMVC/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/fmt.tld", Long.valueOf(1420527028000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsp_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsp_005finput_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsp_005finput_0026_005ftype_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsp_005fselect_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsp_005fradiobuttons_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsp_005fcheckboxes_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsp_005ftextarea_0026_005fpath_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsp_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsp_005finput_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsp_005finput_0026_005ftype_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsp_005fselect_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsp_005fradiobuttons_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsp_005fcheckboxes_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsp_005ftextarea_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fsp_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fsp_005finput_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.release();
    _005fjspx_005ftagPool_005fsp_005finput_0026_005ftype_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fsp_005fselect_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.release();
    _005fjspx_005ftagPool_005fsp_005fradiobuttons_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.release();
    _005fjspx_005ftagPool_005fsp_005fcheckboxes_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.release();
    _005fjspx_005ftagPool_005fsp_005ftextarea_0026_005fpath_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- JSTL 標籤 -->    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Spring Form 表單標籤 -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css\" />\r\n");
      out.write("		<title>User 首頁</title>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body style=\"padding:15px\">\r\n");
      out.write("		<h1>User 資料維護</h1>\r\n");
      out.write("		<hr />\r\n");
      out.write("		<table border=0>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<!-- User 列表 -->\r\n");
      out.write("				<td colspan=\"2\" valign=\"top\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("<!-- JSTL 標籤 -->    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Spring Form 表單標籤 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/buttons/3.0.2/css/buttons.dataTables.css\" />\r\n");
      out.write("<script src=\"https://cdn.datatables.net/2.0.7/js/dataTables.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/buttons/3.0.2/js/buttons.dataTables.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function() { \r\n");
      out.write("		new DataTable('#myTable', {\r\n");
      out.write("		    layout: {\r\n");
      out.write("		        topStart: {\r\n");
      out.write("		            buttons: ['copy', 'csv', 'excel', 'pdf', 'print']\r\n");
      out.write("		        }\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pure-form\">\r\n");
      out.write("	<fieldset>\r\n");
      out.write("		<legend>\r\n");
      out.write("			User List\r\n");
      out.write("		</legend>\r\n");
      out.write("		\r\n");
      out.write("		<!-- User table -->\r\n");
      out.write("		<table id=\"myTable\" class=\"pure-table pure-table-bordered\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>序號</th><th>姓名</th><th>性別</th><th>年齡</th><th>生日</th>\r\n");
      out.write("					<th>教育程度</th><th>興趣</th><th>履歷</th><th>修改</th><th>刪除</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("		\r\n");
      out.write("				\r\n");
      out.write("	</fieldset>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<!-- User 表單 -->\r\n");
      out.write("				<td valign=\"top\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("<!-- JSTL 標籤 -->    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Spring Form 表單標籤 -->\r\n");
      out.write("\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\r');
      out.write('\n');
      //  sp:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_sp_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fsp_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_sp_005fform_005f0_reused = false;
      try {
        _jspx_th_sp_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_sp_005fform_005f0.setParent(null);
        // /WEB-INF/view/user/userform.jspf(9,0) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sp_005fform_005f0.setModelAttribute("user");
        // /WEB-INF/view/user/userform.jspf(9,0) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sp_005fform_005f0.setMethod("post");
        // /WEB-INF/view/user/userform.jspf(9,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sp_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/mvc/user/${ user.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /WEB-INF/view/user/userform.jspf(9,0) null
        _jspx_th_sp_005fform_005f0.setDynamicAttribute(null, "class", "pure-form");
        int[] _jspx_push_body_count_sp_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_sp_005fform_005f0 = _jspx_th_sp_005fform_005f0.doStartTag();
          if (_jspx_eval_sp_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("	<fieldset>\r\n");
              out.write("		<legend>User Form</legend>\r\n");
              out.write("		<!-- HttpMethod 隱藏欄位 -->\r\n");
              out.write("		<input name=\"_method\" type=\"hidden\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" />\r\n");
              out.write("		<!-- 表單元素 -->\r\n");
              out.write("		姓名: ");
              if (_jspx_meth_sp_005finput_005f0(_jspx_th_sp_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sp_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("		     <br>");
              //  sp:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_sp_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_sp_005ferrors_005f0_reused = false;
              try {
                _jspx_th_sp_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_sp_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
                // /WEB-INF/view/user/userform.jspf(16,11) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f0.setPath("name");
                // /WEB-INF/view/user/userform.jspf(16,11) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f0.setCssStyle("color: red");
                int[] _jspx_push_body_count_sp_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_sp_005ferrors_005f0 = _jspx_th_sp_005ferrors_005f0.doStartTag();
                  if (_jspx_th_sp_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sp_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sp_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sp_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.reuse(_jspx_th_sp_005ferrors_005f0);
                _jspx_th_sp_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_sp_005ferrors_005f0_reused);
              }
              out.write("<p />\r\n");
              out.write("		年齡: ");
              if (_jspx_meth_sp_005finput_005f1(_jspx_th_sp_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sp_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("			 <br>");
              //  sp:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_sp_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_sp_005ferrors_005f1_reused = false;
              try {
                _jspx_th_sp_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_sp_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
                // /WEB-INF/view/user/userform.jspf(18,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f1.setPath("age");
                // /WEB-INF/view/user/userform.jspf(18,8) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f1.setCssStyle("color: red");
                int[] _jspx_push_body_count_sp_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_sp_005ferrors_005f1 = _jspx_th_sp_005ferrors_005f1.doStartTag();
                  if (_jspx_th_sp_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sp_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sp_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sp_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.reuse(_jspx_th_sp_005ferrors_005f1);
                _jspx_th_sp_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_sp_005ferrors_005f1_reused);
              }
              out.write("\r\n");
              out.write("			 <p />\r\n");
              out.write("		生日: ");
              if (_jspx_meth_sp_005finput_005f2(_jspx_th_sp_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sp_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("			 <br>");
              //  sp:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_sp_005ferrors_005f2 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_sp_005ferrors_005f2_reused = false;
              try {
                _jspx_th_sp_005ferrors_005f2.setPageContext(_jspx_page_context);
                _jspx_th_sp_005ferrors_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
                // /WEB-INF/view/user/userform.jspf(21,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f2.setPath("birth");
                // /WEB-INF/view/user/userform.jspf(21,8) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f2.setCssStyle("color: red");
                int[] _jspx_push_body_count_sp_005ferrors_005f2 = new int[] { 0 };
                try {
                  int _jspx_eval_sp_005ferrors_005f2 = _jspx_th_sp_005ferrors_005f2.doStartTag();
                  if (_jspx_th_sp_005ferrors_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sp_005ferrors_005f2[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sp_005ferrors_005f2.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sp_005ferrors_005f2.doFinally();
                }
                _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.reuse(_jspx_th_sp_005ferrors_005f2);
                _jspx_th_sp_005ferrors_005f2_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ferrors_005f2, _jsp_getInstanceManager(), _jspx_th_sp_005ferrors_005f2_reused);
              }
              out.write("\r\n");
              out.write("			<p />\r\n");
              out.write("		學歷: ");
              if (_jspx_meth_sp_005fselect_005f0(_jspx_th_sp_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sp_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("			 <br>");
              //  sp:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_sp_005ferrors_005f3 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_sp_005ferrors_005f3_reused = false;
              try {
                _jspx_th_sp_005ferrors_005f3.setPageContext(_jspx_page_context);
                _jspx_th_sp_005ferrors_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
                // /WEB-INF/view/user/userform.jspf(24,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f3.setPath("educationId");
                // /WEB-INF/view/user/userform.jspf(24,8) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f3.setCssStyle("color: red");
                int[] _jspx_push_body_count_sp_005ferrors_005f3 = new int[] { 0 };
                try {
                  int _jspx_eval_sp_005ferrors_005f3 = _jspx_th_sp_005ferrors_005f3.doStartTag();
                  if (_jspx_th_sp_005ferrors_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sp_005ferrors_005f3[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sp_005ferrors_005f3.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sp_005ferrors_005f3.doFinally();
                }
                _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.reuse(_jspx_th_sp_005ferrors_005f3);
                _jspx_th_sp_005ferrors_005f3_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ferrors_005f3, _jsp_getInstanceManager(), _jspx_th_sp_005ferrors_005f3_reused);
              }
              out.write("\r\n");
              out.write("			<p />\r\n");
              out.write("		性別: ");
              if (_jspx_meth_sp_005fradiobuttons_005f0(_jspx_th_sp_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sp_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("			 <br>");
              //  sp:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_sp_005ferrors_005f4 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_sp_005ferrors_005f4_reused = false;
              try {
                _jspx_th_sp_005ferrors_005f4.setPageContext(_jspx_page_context);
                _jspx_th_sp_005ferrors_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
                // /WEB-INF/view/user/userform.jspf(27,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f4.setPath("genderId");
                // /WEB-INF/view/user/userform.jspf(27,8) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f4.setCssStyle("color: red");
                int[] _jspx_push_body_count_sp_005ferrors_005f4 = new int[] { 0 };
                try {
                  int _jspx_eval_sp_005ferrors_005f4 = _jspx_th_sp_005ferrors_005f4.doStartTag();
                  if (_jspx_th_sp_005ferrors_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sp_005ferrors_005f4[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sp_005ferrors_005f4.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sp_005ferrors_005f4.doFinally();
                }
                _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.reuse(_jspx_th_sp_005ferrors_005f4);
                _jspx_th_sp_005ferrors_005f4_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ferrors_005f4, _jsp_getInstanceManager(), _jspx_th_sp_005ferrors_005f4_reused);
              }
              out.write("\r\n");
              out.write("			<p />\r\n");
              out.write("		興趣: ");
              if (_jspx_meth_sp_005fcheckboxes_005f0(_jspx_th_sp_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sp_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("			 <br>");
              //  sp:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_sp_005ferrors_005f5 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_sp_005ferrors_005f5_reused = false;
              try {
                _jspx_th_sp_005ferrors_005f5.setPageContext(_jspx_page_context);
                _jspx_th_sp_005ferrors_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
                // /WEB-INF/view/user/userform.jspf(30,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f5.setPath("interestIds");
                // /WEB-INF/view/user/userform.jspf(30,8) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f5.setCssStyle("color: red");
                int[] _jspx_push_body_count_sp_005ferrors_005f5 = new int[] { 0 };
                try {
                  int _jspx_eval_sp_005ferrors_005f5 = _jspx_th_sp_005ferrors_005f5.doStartTag();
                  if (_jspx_th_sp_005ferrors_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sp_005ferrors_005f5[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sp_005ferrors_005f5.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sp_005ferrors_005f5.doFinally();
                }
                _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.reuse(_jspx_th_sp_005ferrors_005f5);
                _jspx_th_sp_005ferrors_005f5_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ferrors_005f5, _jsp_getInstanceManager(), _jspx_th_sp_005ferrors_005f5_reused);
              }
              out.write("\r\n");
              out.write("			<p />\r\n");
              out.write("		履歷: ");
              if (_jspx_meth_sp_005ftextarea_005f0(_jspx_th_sp_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sp_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("			 <br>");
              //  sp:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_sp_005ferrors_005f6 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_sp_005ferrors_005f6_reused = false;
              try {
                _jspx_th_sp_005ferrors_005f6.setPageContext(_jspx_page_context);
                _jspx_th_sp_005ferrors_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
                // /WEB-INF/view/user/userform.jspf(33,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f6.setPath("resume");
                // /WEB-INF/view/user/userform.jspf(33,8) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f6.setCssStyle("color: red");
                int[] _jspx_push_body_count_sp_005ferrors_005f6 = new int[] { 0 };
                try {
                  int _jspx_eval_sp_005ferrors_005f6 = _jspx_th_sp_005ferrors_005f6.doStartTag();
                  if (_jspx_th_sp_005ferrors_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sp_005ferrors_005f6[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sp_005ferrors_005f6.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sp_005ferrors_005f6.doFinally();
                }
                _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.reuse(_jspx_th_sp_005ferrors_005f6);
                _jspx_th_sp_005ferrors_005f6_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ferrors_005f6, _jsp_getInstanceManager(), _jspx_th_sp_005ferrors_005f6_reused);
              }
              out.write("\r\n");
              out.write("			<p />\r\n");
              out.write("		<button type=\"submit\" class=\"pure-button pure-button-primary\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method eq 'PUT' ? '修改' : '新增' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</button>\r\n");
              out.write("		<p />\r\n");
              out.write("		<!-- 顯示所有錯誤訊息 -->\r\n");
              out.write("		");
              //  sp:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_sp_005ferrors_005f7 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_sp_005ferrors_005f7_reused = false;
              try {
                _jspx_th_sp_005ferrors_005f7.setPageContext(_jspx_page_context);
                _jspx_th_sp_005ferrors_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
                // /WEB-INF/view/user/userform.jspf(38,2) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f7.setPath("*");
                // /WEB-INF/view/user/userform.jspf(38,2) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sp_005ferrors_005f7.setCssStyle("color: red");
                int[] _jspx_push_body_count_sp_005ferrors_005f7 = new int[] { 0 };
                try {
                  int _jspx_eval_sp_005ferrors_005f7 = _jspx_th_sp_005ferrors_005f7.doStartTag();
                  if (_jspx_th_sp_005ferrors_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sp_005ferrors_005f7[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sp_005ferrors_005f7.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sp_005ferrors_005f7.doFinally();
                }
                _005fjspx_005ftagPool_005fsp_005ferrors_0026_005fpath_005fcssStyle_005fnobody.reuse(_jspx_th_sp_005ferrors_005f7);
                _jspx_th_sp_005ferrors_005f7_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ferrors_005f7, _jsp_getInstanceManager(), _jspx_th_sp_005ferrors_005f7_reused);
              }
              out.write("\r\n");
              out.write("	</fieldset>\r\n");
              out.write("	\r\n");
              int evalDoAfterBody = _jspx_th_sp_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_sp_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_sp_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_sp_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_sp_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fsp_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.reuse(_jspx_th_sp_005fform_005f0);
        _jspx_th_sp_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_sp_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<!-- User 圖表 -->\r\n");
      out.write("				<td valign=\"top\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("<!-- JSTL 標籤 -->    \r\n");
      out.write("\r\n");
      out.write("<!-- 統計資料 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  google.charts.load('current', {'packages':['corechart']});\r\n");
      out.write("  google.charts.setOnLoadCallback(drawChart);\r\n");
      out.write("\r\n");
      out.write("  function drawChart() {\r\n");
      out.write("	  drawEducationChart();\r\n");
      out.write("	  drawGenderChart();\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function drawEducationChart() {\r\n");
      out.write("	var data = google.visualization.arrayToDataTable([\r\n");
      out.write("	      ['Item', 'Count'],\r\n");
      out.write("	      \r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      	\r\n");
      out.write("    ]);\r\n");
      out.write("\r\n");
      out.write("    var options = {\r\n");
      out.write("      title: 'Education Statistics',\r\n");
      out.write("      is3D: true\r\n");
      out.write("    };\r\n");
      out.write("	// PieChart, BarChart, ColumnChart, LineChart\r\n");
      out.write("    var chart = new google.visualization.PieChart(document.getElementById('educationchart'));\r\n");
      out.write("\r\n");
      out.write("    chart.draw(data, options);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function drawGenderChart() {\r\n");
      out.write("\r\n");
      out.write("    var data = google.visualization.arrayToDataTable([\r\n");
      out.write("      ['Item', 'Count'],\r\n");
      out.write("      \r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      	\r\n");
      out.write("    ]);\r\n");
      out.write("\r\n");
      out.write("    var options = {\r\n");
      out.write("      title: 'Gender Statistics'\r\n");
      out.write("    };\r\n");
      out.write("	// PieChart, BarChart, ColumnChart, LineChart\r\n");
      out.write("    var chart = new google.visualization.BarChart(document.getElementById('genderchart'));\r\n");
      out.write("\r\n");
      out.write("    chart.draw(data, options);\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("<table>\r\n");
      out.write("	<td valign=\"top\">\r\n");
      out.write("		<div id=\"genderchart\" style=\"width: 700px; height: 500px;\"></div>\r\n");
      out.write("	</td>\r\n");
      out.write("	<td valign=\"top\">\r\n");
      out.write("		<div id=\"educationchart\" style=\"width: 700px; height: 500px;\"></div>\r\n");
      out.write("	</td>	\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/user/userlist.jspf(49,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/user/userlist.jspf(49,4) '${ userDtos }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ userDtos }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/user/userlist.jspf(49,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("userDto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<tr>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.gender.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.age }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.education.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.interestNames }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.resume }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>\r\n");
            out.write("							<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/mvc/user/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"pure-button\">修改</a>\r\n");
            out.write("						</td>\r\n");
            out.write("						<td>\r\n");
            out.write("							<!-- 刪除 from 表單 -->\r\n");
            out.write("							<form method=\"post\" action=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/mvc/user/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("								<input name=\"_method\" type=\"hidden\" value=\"DELETE\">\r\n");
            out.write("								<button type=\"submit\" class=\"pure-button\">刪除</button>\r\n");
            out.write("							</form>\r\n");
            out.write("						</td>\r\n");
            out.write("					</tr>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/user/userlist.jspf(55,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userDto.birth }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/user/userlist.jspf(55,10) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sp_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sp_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sp_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sp:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sp_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsp_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_sp_005finput_005f0_reused = false;
    try {
      _jspx_th_sp_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sp_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
      // /WEB-INF/view/user/userform.jspf(15,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005finput_005f0.setPath("name");
      int[] _jspx_push_body_count_sp_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sp_005finput_005f0 = _jspx_th_sp_005finput_005f0.doStartTag();
        if (_jspx_th_sp_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sp_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sp_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sp_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsp_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_sp_005finput_005f0);
      _jspx_th_sp_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_sp_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sp_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sp_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sp_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sp:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sp_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsp_005finput_0026_005ftype_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_sp_005finput_005f1_reused = false;
    try {
      _jspx_th_sp_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sp_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
      // /WEB-INF/view/user/userform.jspf(17,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005finput_005f1.setPath("age");
      // /WEB-INF/view/user/userform.jspf(17,6) null
      _jspx_th_sp_005finput_005f1.setDynamicAttribute(null, "type", "number");
      int[] _jspx_push_body_count_sp_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sp_005finput_005f1 = _jspx_th_sp_005finput_005f1.doStartTag();
        if (_jspx_th_sp_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sp_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sp_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sp_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fsp_005finput_0026_005ftype_005fpath_005fnobody.reuse(_jspx_th_sp_005finput_005f1);
      _jspx_th_sp_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_sp_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sp_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sp_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sp_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sp:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sp_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsp_005finput_0026_005ftype_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_sp_005finput_005f2_reused = false;
    try {
      _jspx_th_sp_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sp_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
      // /WEB-INF/view/user/userform.jspf(20,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005finput_005f2.setPath("birth");
      // /WEB-INF/view/user/userform.jspf(20,6) null
      _jspx_th_sp_005finput_005f2.setDynamicAttribute(null, "type", "date");
      int[] _jspx_push_body_count_sp_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_sp_005finput_005f2 = _jspx_th_sp_005finput_005f2.doStartTag();
        if (_jspx_th_sp_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sp_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sp_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sp_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fsp_005finput_0026_005ftype_005fpath_005fnobody.reuse(_jspx_th_sp_005finput_005f2);
      _jspx_th_sp_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_sp_005finput_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sp_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sp_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sp_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sp:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_sp_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fsp_005fselect_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    boolean _jspx_th_sp_005fselect_005f0_reused = false;
    try {
      _jspx_th_sp_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sp_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
      // /WEB-INF/view/user/userform.jspf(23,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fselect_005f0.setPath("educationId");
      // /WEB-INF/view/user/userform.jspf(23,6) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fselect_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ educations }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/user/userform.jspf(23,6) name = itemValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fselect_005f0.setItemValue("id");
      // /WEB-INF/view/user/userform.jspf(23,6) name = itemLabel type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fselect_005f0.setItemLabel("name");
      int[] _jspx_push_body_count_sp_005fselect_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sp_005fselect_005f0 = _jspx_th_sp_005fselect_005f0.doStartTag();
        if (_jspx_th_sp_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sp_005fselect_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sp_005fselect_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sp_005fselect_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsp_005fselect_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.reuse(_jspx_th_sp_005fselect_005f0);
      _jspx_th_sp_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_sp_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sp_005fradiobuttons_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sp_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sp_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sp:radiobuttons
    org.springframework.web.servlet.tags.form.RadioButtonsTag _jspx_th_sp_005fradiobuttons_005f0 = (org.springframework.web.servlet.tags.form.RadioButtonsTag) _005fjspx_005ftagPool_005fsp_005fradiobuttons_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonsTag.class);
    boolean _jspx_th_sp_005fradiobuttons_005f0_reused = false;
    try {
      _jspx_th_sp_005fradiobuttons_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sp_005fradiobuttons_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
      // /WEB-INF/view/user/userform.jspf(26,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fradiobuttons_005f0.setPath("genderId");
      // /WEB-INF/view/user/userform.jspf(26,6) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fradiobuttons_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ genders }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/user/userform.jspf(26,6) name = itemValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fradiobuttons_005f0.setItemValue("id");
      // /WEB-INF/view/user/userform.jspf(26,6) name = itemLabel type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fradiobuttons_005f0.setItemLabel("name");
      int[] _jspx_push_body_count_sp_005fradiobuttons_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sp_005fradiobuttons_005f0 = _jspx_th_sp_005fradiobuttons_005f0.doStartTag();
        if (_jspx_th_sp_005fradiobuttons_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sp_005fradiobuttons_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sp_005fradiobuttons_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sp_005fradiobuttons_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsp_005fradiobuttons_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.reuse(_jspx_th_sp_005fradiobuttons_005f0);
      _jspx_th_sp_005fradiobuttons_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005fradiobuttons_005f0, _jsp_getInstanceManager(), _jspx_th_sp_005fradiobuttons_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sp_005fcheckboxes_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sp_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sp_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sp:checkboxes
    org.springframework.web.servlet.tags.form.CheckboxesTag _jspx_th_sp_005fcheckboxes_005f0 = (org.springframework.web.servlet.tags.form.CheckboxesTag) _005fjspx_005ftagPool_005fsp_005fcheckboxes_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxesTag.class);
    boolean _jspx_th_sp_005fcheckboxes_005f0_reused = false;
    try {
      _jspx_th_sp_005fcheckboxes_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sp_005fcheckboxes_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
      // /WEB-INF/view/user/userform.jspf(29,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fcheckboxes_005f0.setPath("interestIds");
      // /WEB-INF/view/user/userform.jspf(29,6) name = items type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fcheckboxes_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ interests }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/user/userform.jspf(29,6) name = itemValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fcheckboxes_005f0.setItemValue("id");
      // /WEB-INF/view/user/userform.jspf(29,6) name = itemLabel type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005fcheckboxes_005f0.setItemLabel("name");
      int[] _jspx_push_body_count_sp_005fcheckboxes_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sp_005fcheckboxes_005f0 = _jspx_th_sp_005fcheckboxes_005f0.doStartTag();
        if (_jspx_th_sp_005fcheckboxes_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sp_005fcheckboxes_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sp_005fcheckboxes_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sp_005fcheckboxes_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsp_005fcheckboxes_0026_005fpath_005fitems_005fitemValue_005fitemLabel_005fnobody.reuse(_jspx_th_sp_005fcheckboxes_005f0);
      _jspx_th_sp_005fcheckboxes_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005fcheckboxes_005f0, _jsp_getInstanceManager(), _jspx_th_sp_005fcheckboxes_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sp_005ftextarea_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sp_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sp_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sp:textarea
    org.springframework.web.servlet.tags.form.TextareaTag _jspx_th_sp_005ftextarea_005f0 = (org.springframework.web.servlet.tags.form.TextareaTag) _005fjspx_005ftagPool_005fsp_005ftextarea_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.TextareaTag.class);
    boolean _jspx_th_sp_005ftextarea_005f0_reused = false;
    try {
      _jspx_th_sp_005ftextarea_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sp_005ftextarea_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sp_005fform_005f0);
      // /WEB-INF/view/user/userform.jspf(32,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sp_005ftextarea_005f0.setPath("resume");
      int[] _jspx_push_body_count_sp_005ftextarea_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sp_005ftextarea_005f0 = _jspx_th_sp_005ftextarea_005f0.doStartTag();
        if (_jspx_th_sp_005ftextarea_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sp_005ftextarea_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sp_005ftextarea_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sp_005ftextarea_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsp_005ftextarea_0026_005fpath_005fnobody.reuse(_jspx_th_sp_005ftextarea_005f0);
      _jspx_th_sp_005ftextarea_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sp_005ftextarea_005f0, _jsp_getInstanceManager(), _jspx_th_sp_005ftextarea_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/view/user/userstatistics.jspf(20,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/user/userstatistics.jspf(20,6) '${ educationStatistics }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ educationStatistics }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/user/userstatistics.jspf(20,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      	['");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stat.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stat.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("],\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/view/user/userstatistics.jspf(41,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/user/userstatistics.jspf(41,6) '${ genderStatistics }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ genderStatistics }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/user/userstatistics.jspf(41,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      	['");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stat.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stat.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("],\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
